### ISSUE TITLE
callback must accept string parameters

### ISSUE THREAD

**Issue by dansmith65** [jwillinghalpern/fm-gofer#16]
https://github.com/jwillinghalpern/fm-gofer/blob/65a9e593c6715c173bd0d897700ef4b2a77ce71e/src/index.js#L66

> Parameters are one or more optional text parameters to pass to the JavaScript function.

— https://help.claris.com/en/pro-help/content/perform-javascript-in-web-viewer.html

Currently, you can't pass a 3rd parameter otherwise it'll fail.

**Comment by jwillinghalpern** [comment]
I don't quite understand.

~~Wasn't that the goal, that if a third parameter was passed to the callback, it would reject the promise?~~

I'll check when back, but maybe the problem is that the third param is getting passed in as "0" which is being evaluated as truthy.

**Comment by jwillinghalpern** [comment]
As of this commit, you can pass "0" as the third param to the callback and it will still resolve the promise. We treat "0" as falsey here.
https://github.com/jwillinghalpern/fm-gofer/commit/04cbcef4c11d99e793c4ce1825c86b69d82f2e17#diff-bfe9874d239014961b1ae4e89875a6155667db834a410aaaa2ebe3cf89820556R68
